### ISSUE TITLE
Screenshot on level up

### ISSUE THREAD

**Issue by Dablakbandit** [cabbagegod/cabbagescape#13]
Mod should have the runelite function of screenshotting when leveling skills.

Possible addition of a separate screenshot folder to distinguish the screenshots.

**Comment by cabbagegod** [comment]
Added in 31e955d2c4d7239f24e04ebd2bf132e907660e77. You can find the screenshots in `.minecraft/cabbagescape/screenshots`

Thank you for the suggestion mr bandit ;)
